version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5251:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      AllowedHosts: "*"
      ConnectionString: "Server=postgres;Port=5432;Database=test_db;User Id=test_user;Password=wololo;"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: wololo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: